debug: false

invsee:
  enabled: true
  allow-offline: true
  allow-modify: true
  title: "&bInvsee &7• &f{player}"
  rows: 6

  layout:
    slots:
      helmet: 46
      chestplate: 47
      leggings: 48
      boots: 49
      offhand: 53

    label-slots:
      helmet: 37
      chestplate: 38
      leggings: 39
      boots: 40
      offhand: 44

    labels:
      helmet: "&bHelm"
      chestplate: "&bChestplate"
      leggings: "&bLeggings"
      boots: "&bBoots"
      offhand: "&bOffhand"

enderchest:
  enabled: true
  allow-offline: true
  allow-modify: true
  title: "&bEnderchest &7• &f{player}"

leave-tracking:
  enabled: true
  classify-kicks: true
  fallback-quit-reason: "QUIT"

restart:
  timezone: "Europe/Brussels"
  enabled: true

  auto:
    enabled: true
    times:
      - "03:00"
      - "15:00"
    skip-if-planned-running: true
    default-reason: "Automatische restart"

  announce-seconds:
    - 3600
    - 1800
    - 600
    - 300
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1

  title:
    enabled: true
    fade-in: 10
    stay: 40
    fade-out: 10

  disconnect:
    enabled: true

  action:
    type: "stop"
    command: "stop"

planrestart:
  allow-override: true
  default-reason: "Geen reden opgegeven."

maintenance:
  enabled: false

whois:
  enabled: true

  hooks:
    essentials: true
    placeholderapi: true

  placeholders:
    balance: "%vault_eco_balance_formatted%"
    level: "%lekkerleveling_level%"

  pages:
    default-page: 1
    max-pages: 2
    clickable-navigation: true

  fields:
    minecraft-name: true
    nickname: true
    mc-uuid: true
    discord-name: true
    discord-id: true
    location: true
    playtime: true
    last-online: true
    balance: true
    ip: true
    hp: true
    hunger: true
    exp: true
    whitelist-status: true
    gamemode: true
    god: true
    fly: true
    speed: true
    jailed: true
    muted: true
    afk: true
    op: true
    alt-accounts: true
    level: true

  layout:
    page-1:
      - minecraft-name
      - nickname
      - mc-uuid
      - discord-name
      - discord-id
      - whitelist-status
      - gamemode
      - op
      - level
      - balance
      - playtime
      - last-online
    page-2:
      - location
      - hp
      - hunger
      - exp
      - god
      - fly
      - speed
      - jailed
      - muted
      - afk
      - ip
      - alt-accounts

vanish:
  enabled: true
  persistent: true

  bossbar:
    enabled: true
    title: "&bJe bent momenteel in vanish"
    color: "PURPLE"
    style: "SOLID"

  staff-visibility:
    enabled: true
    glow-for-staff: true

  hide:
    suppress-join-message: true
    suppress-quit-message: true
    block-mob-targeting: true
    block-item-pickup: true
    hide-dropped-items: true

  logging:
    enabled: true